/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Prediction = IDL.Variant({ 'Fake' : IDL.Null, 'Real' : IDL.Null });
export const ClassificationResult = IDL.Record({
  'prediction' : Prediction,
  'reviewText' : IDL.Text,
  'confidence' : IDL.Nat,
  'suspiciousWords' : IDL.Vec(IDL.Text),
});
export const DailyBreakdown = IDL.Record({
  'date' : IDL.Text,
  'realCount' : IDL.Nat,
  'fakeCount' : IDL.Nat,
});
export const AnalyticsSummary = IDL.Record({
  'realCount' : IDL.Nat,
  'fakeCount' : IDL.Nat,
  'dailyBreakdown' : IDL.Vec(DailyBreakdown),
  'totalReviews' : IDL.Nat,
});
export const ReviewFilter = IDL.Variant({
  'All' : IDL.Null,
  'Fake' : IDL.Null,
  'Real' : IDL.Null,
});
export const PaginationParams = IDL.Record({
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
});
export const ReviewId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ReviewResult = IDL.Record({
  'id' : ReviewId,
  'prediction' : Prediction,
  'reviewText' : IDL.Text,
  'timestamp' : Timestamp,
  'confidence' : IDL.Nat,
  'suspiciousWords' : IDL.Vec(IDL.Text),
});
export const ReviewPage = IDL.Record({
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(ReviewResult),
  'totalPages' : IDL.Nat,
  'totalItems' : IDL.Nat,
});
export const ContactInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkClassify' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(ClassificationResult)],
      [],
    ),
  'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text }))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReviewHistory' : IDL.Func(
      [ReviewFilter, PaginationParams],
      [ReviewPage],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text }))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text })],
      [],
      [],
    ),
  'submitContact' : IDL.Func([ContactInput], [IDL.Bool], []),
  'submitReview' : IDL.Func([IDL.Text], [ReviewResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Prediction = IDL.Variant({ 'Fake' : IDL.Null, 'Real' : IDL.Null });
  const ClassificationResult = IDL.Record({
    'prediction' : Prediction,
    'reviewText' : IDL.Text,
    'confidence' : IDL.Nat,
    'suspiciousWords' : IDL.Vec(IDL.Text),
  });
  const DailyBreakdown = IDL.Record({
    'date' : IDL.Text,
    'realCount' : IDL.Nat,
    'fakeCount' : IDL.Nat,
  });
  const AnalyticsSummary = IDL.Record({
    'realCount' : IDL.Nat,
    'fakeCount' : IDL.Nat,
    'dailyBreakdown' : IDL.Vec(DailyBreakdown),
    'totalReviews' : IDL.Nat,
  });
  const ReviewFilter = IDL.Variant({
    'All' : IDL.Null,
    'Fake' : IDL.Null,
    'Real' : IDL.Null,
  });
  const PaginationParams = IDL.Record({
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
  });
  const ReviewId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ReviewResult = IDL.Record({
    'id' : ReviewId,
    'prediction' : Prediction,
    'reviewText' : IDL.Text,
    'timestamp' : Timestamp,
    'confidence' : IDL.Nat,
    'suspiciousWords' : IDL.Vec(IDL.Text),
  });
  const ReviewPage = IDL.Record({
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(ReviewResult),
    'totalPages' : IDL.Nat,
    'totalItems' : IDL.Nat,
  });
  const ContactInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkClassify' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(ClassificationResult)],
        [],
      ),
    'deleteReview' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAnalytics' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text }))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReviewHistory' : IDL.Func(
        [ReviewFilter, PaginationParams],
        [ReviewPage],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text }))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text })],
        [],
        [],
      ),
    'submitContact' : IDL.Func([ContactInput], [IDL.Bool], []),
    'submitReview' : IDL.Func([IDL.Text], [ReviewResult], []),
  });
};

export const init = ({ IDL }) => { return []; };