/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'realCount' : bigint,
  'fakeCount' : bigint,
  'dailyBreakdown' : Array<DailyBreakdown>,
  'totalReviews' : bigint,
}
export interface ClassificationResult {
  'prediction' : Prediction,
  'reviewText' : string,
  'confidence' : bigint,
  'suspiciousWords' : Array<string>,
}
export interface ContactInput {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface DailyBreakdown {
  'date' : string,
  'realCount' : bigint,
  'fakeCount' : bigint,
}
export interface PaginationParams { 'page' : bigint, 'pageSize' : bigint }
export type Prediction = { 'Fake' : null } |
  { 'Real' : null };
export type ReviewFilter = { 'All' : null } |
  { 'Fake' : null } |
  { 'Real' : null };
export type ReviewId = bigint;
export interface ReviewPage {
  'page' : bigint,
  'pageSize' : bigint,
  'items' : Array<ReviewResult>,
  'totalPages' : bigint,
  'totalItems' : bigint,
}
export interface ReviewResult {
  'id' : ReviewId,
  'prediction' : Prediction,
  'reviewText' : string,
  'timestamp' : Timestamp,
  'confidence' : bigint,
  'suspiciousWords' : Array<string>,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
/**
 * / Composition root for the Fake Review Detection System canister.
 * /
 * / Wires together:
 * /   - Authorization (Internet Identity via caffeineai-authorization)
 * /   - User profiles
 * /   - Review submission, history, analytics, and CSV bulk classification
 * /   - Contact form storage
 * /
 * / No business logic lives here — all implementation is in lib/ and mixins/.
 */
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkClassify' : ActorMethod<[Array<string>], Array<ClassificationResult>>,
  'deleteReview' : ActorMethod<[bigint], boolean>,
  'getAnalytics' : ActorMethod<[], AnalyticsSummary>,
  'getCallerUserProfile' : ActorMethod<
    [],
    [] | [{ 'username' : string, 'name' : string }]
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReviewHistory' : ActorMethod<
    [ReviewFilter, PaginationParams],
    ReviewPage
  >,
  'getUserProfile' : ActorMethod<
    [Principal],
    [] | [{ 'username' : string, 'name' : string }]
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [{ 'username' : string, 'name' : string }],
    undefined
  >,
  'submitContact' : ActorMethod<[ContactInput], boolean>,
  'submitReview' : ActorMethod<[string], ReviewResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];