/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PaginationParams {
    page: bigint;
    pageSize: bigint;
}
export interface ContactInput {
    name: string;
    email: string;
    message: string;
}
export type Timestamp = bigint;
export interface AnalyticsSummary {
    realCount: bigint;
    fakeCount: bigint;
    dailyBreakdown: Array<DailyBreakdown>;
    totalReviews: bigint;
}
export interface DailyBreakdown {
    date: string;
    realCount: bigint;
    fakeCount: bigint;
}
export interface ClassificationResult {
    prediction: Prediction;
    reviewText: string;
    confidence: bigint;
    suspiciousWords: Array<string>;
}
export interface ReviewPage {
    page: bigint;
    pageSize: bigint;
    items: Array<ReviewResult>;
    totalPages: bigint;
    totalItems: bigint;
}
export type ReviewId = bigint;
export interface ReviewResult {
    id: ReviewId;
    prediction: Prediction;
    reviewText: string;
    timestamp: Timestamp;
    confidence: bigint;
    suspiciousWords: Array<string>;
}
export enum Prediction {
    Fake = "Fake",
    Real = "Real"
}
export enum ReviewFilter {
    All = "All",
    Fake = "Fake",
    Real = "Real"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
/**
 * / Composition root for the Fake Review Detection System canister.
 * /
 * / Wires together:
 * /   - Authorization (Internet Identity via caffeineai-authorization)
 * /   - User profiles
 * /   - Review submission, history, analytics, and CSV bulk classification
 * /   - Contact form storage
 * /
 * / No business logic lives here — all implementation is in lib/ and mixins/.
 */
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkClassify(texts: Array<string>): Promise<Array<ClassificationResult>>;
    deleteReview(id: bigint): Promise<boolean>;
    getAnalytics(): Promise<AnalyticsSummary>;
    getCallerUserProfile(): Promise<{
        username: string;
        name: string;
    } | null>;
    getCallerUserRole(): Promise<UserRole>;
    getReviewHistory(filter: ReviewFilter, pagination: PaginationParams): Promise<ReviewPage>;
    getUserProfile(user: Principal): Promise<{
        username: string;
        name: string;
    } | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: {
        username: string;
        name: string;
    }): Promise<void>;
    submitContact(input: ContactInput): Promise<boolean>;
    submitReview(reviewText: string): Promise<ReviewResult>;
}
import type { ClassificationResult as _ClassificationResult, Prediction as _Prediction, ReviewFilter as _ReviewFilter, ReviewId as _ReviewId, ReviewPage as _ReviewPage, ReviewResult as _ReviewResult, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkClassify(arg0: Array<string>): Promise<Array<ClassificationResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkClassify(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkClassify(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteReview(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async getAnalytics(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<{
        username: string;
        name: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewHistory(arg0: ReviewFilter, arg1: PaginationParams): Promise<ReviewPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewHistory(to_candid_ReviewFilter_n11(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_ReviewPage_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewHistory(to_candid_ReviewFilter_n11(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_ReviewPage_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<{
        username: string;
        name: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: {
        username: string;
        name: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContact(arg0: ContactInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async submitReview(arg0: string): Promise<ReviewResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0);
                return from_candid_ReviewResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0);
            return from_candid_ReviewResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ClassificationResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassificationResult): ClassificationResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Prediction_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prediction): Prediction {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewPage_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewPage): ReviewPage {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ReviewResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewResult): ReviewResult {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        username: string;
        name: string;
    }]): {
    username: string;
    name: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    page: bigint;
    pageSize: bigint;
    items: Array<_ReviewResult>;
    totalPages: bigint;
    totalItems: bigint;
}): {
    page: bigint;
    pageSize: bigint;
    items: Array<ReviewResult>;
    totalPages: bigint;
    totalItems: bigint;
} {
    return {
        page: value.page,
        pageSize: value.pageSize,
        items: from_candid_vec_n15(_uploadFile, _downloadFile, value.items),
        totalPages: value.totalPages,
        totalItems: value.totalItems
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReviewId;
    prediction: _Prediction;
    reviewText: string;
    timestamp: _Timestamp;
    confidence: bigint;
    suspiciousWords: Array<string>;
}): {
    id: ReviewId;
    prediction: Prediction;
    reviewText: string;
    timestamp: Timestamp;
    confidence: bigint;
    suspiciousWords: Array<string>;
} {
    return {
        id: value.id,
        prediction: from_candid_Prediction_n6(_uploadFile, _downloadFile, value.prediction),
        reviewText: value.reviewText,
        timestamp: value.timestamp,
        confidence: value.confidence,
        suspiciousWords: value.suspiciousWords
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prediction: _Prediction;
    reviewText: string;
    confidence: bigint;
    suspiciousWords: Array<string>;
}): {
    prediction: Prediction;
    reviewText: string;
    confidence: bigint;
    suspiciousWords: Array<string>;
} {
    return {
        prediction: from_candid_Prediction_n6(_uploadFile, _downloadFile, value.prediction),
        reviewText: value.reviewText,
        confidence: value.confidence,
        suspiciousWords: value.suspiciousWords
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Fake: null;
} | {
    Real: null;
}): Prediction {
    return "Fake" in value ? Prediction.Fake : "Real" in value ? Prediction.Real : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReviewResult>): Array<ReviewResult> {
    return value.map((x)=>from_candid_ReviewResult_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClassificationResult>): Array<ClassificationResult> {
    return value.map((x)=>from_candid_ClassificationResult_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ReviewFilter_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewFilter): _ReviewFilter {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewFilter): {
    All: null;
} | {
    Fake: null;
} | {
    Real: null;
} {
    return value == ReviewFilter.All ? {
        All: null
    } : value == ReviewFilter.Fake ? {
        Fake: null
    } : value == ReviewFilter.Real ? {
        Real: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
